#!/usr/bin/env bash

set -e
set -o pipefail
set -u

FILES() {
    git ls-files --cached --exclude-standard | grep -v vendor
}

match() {
    grep -E "${1}" || true
}

FILES | match '\.(cpp|c|h)$' | xargs clang-format -i
